import json
import os
import subprocess
import sys

import chromadb
import pyautogui
import requests

# Optional dependency check for window manipulation
try:
    import pygetwindow as gw
except ImportError:
    gw = None

OLLAMA_URL = "http://localhost:11434/api/generate"
MODEL_NAME = "llama3.1:8b-instruct-q4_K_M"
MAX_HEALING_ATTEMPTS = 3

FRIDAY_OS_DIR = os.path.expanduser("~/FridayOS_Workspace")
os.makedirs(FRIDAY_OS_DIR, exist_ok=True)

# 1. Initialize Long-Term Macro Vector Storage
CHROMA_DIR = os.path.join(FRIDAY_OS_DIR, "chroma_db")
chroma_client = chromadb.PersistentClient(path=CHROMA_DIR)
# Collection to index successful user intents to written python code snippets
macro_collection = chroma_client.get_or_create_collection(
    name="friday_automation_macros"
)

SYSTEM_PROMPT = """You are the autonomous executor engine for FridayOS. You have NO external APIs.
Your job is to read tasks generated by the OS, execute the required UI steps via pyautogui,
and log your completion status. You must write clean scripts to execute tasks.

You can respond with raw python code wrapped in markdown code blocks like ```python ... ```, 
or a raw text sequence that can be parsed as a script."""


def extract_clean_code(raw_text: str) -> str:
    """
    Safely extracts executable python segments regardless of how messy
    or conversational the local model's response is.
    """
    cleaned = raw_text.strip()

    # Check if the model responded with a stringified JSON dictionary
    try:
        data = json.loads(cleaned)
        if isinstance(data, dict) and "code" in data:
            return str(data["code"]).strip()
    except Exception:
        pass

    # Standard Markdown Code Block Extractor (```python ... ```)
    if "```python" in cleaned:
        try:
            parts = cleaned.split("```python")
            if len(parts) > 1:
                return parts[1].split("```")[0].strip()
        except Exception:
            pass

    # Generic Code Block Extractor (``` ... ```)
    if "```" in cleaned:
        try:
            parts = cleaned.split("```")
            if len(parts) > 1:
                return parts[1].split("```")[0].strip()
        except Exception:
            pass

    # Fallback Strategy: If it contains standard pyautogui code lines, treat the whole text as code
    if "import pyautogui" in cleaned or "pyautogui." in cleaned:
        # Strip out conversational lines if they exist at the top/bottom
        lines = cleaned.split("\n")
        code_lines = [
            line
            for line in lines
            if not line.strip().startswith(("Here", "Sure", "This script", "Note:"))
        ]
        return "\n".join(code_lines).strip()

    return cleaned


def ask_local_brain(prompt: str) -> str:
    """Queries Ollama and grabs the raw text response."""
    payload = {
        "model": MODEL_NAME,
        "prompt": prompt,
        "system": SYSTEM_PROMPT,
        "stream": False,
    }
    try:
        response = requests.post(OLLAMA_URL, json=payload, timeout=45)
        return response.json().get("response", "").strip()
    except Exception as e:
        return f"# Error communicating with Ollama: {str(e)}"


def bring_window_to_front(window_keyword: str) -> bool:
    """
    Feature 2: Uses PyGetWindow to locate and visually isolate the target application window
    before running keyboard and mouse macros.
    """
    if not gw or not window_keyword:
        return False
    try:
        print(
            f"[*] Visual Sandbox: Attempting to isolate target window matching '{window_keyword}'..."
        )
        windows = gw.getWindowsWithTitle(window_keyword)
        if windows:
            target_win = windows[0]
            if target_win.isMinimized:
                target_win.restore()
            target_win.activate()
            # Log bounding geometry coordinates for model awareness
            print(
                f"[✔] Isolated window: '{target_win.title}' at Coordinates X:{target_win.left}, Y:{target_win.top} [Width: {target_win.width}, Height: {target_win.height}]"
            )
            return True
        print(
            f"[!] Visual Sandbox: No active windows found matching keyword: '{window_keyword}'"
        )
        return False
    except Exception as e:
        print(f"[!] Visual Sandbox Error: {str(e)}")
        return False


def main():
    print("[*] Synchronizing Local Self-Evolution Loop with FridayOS...")

    task_file = os.path.join(FRIDAY_OS_DIR, "friday_tasks.json")
    if not os.path.exists(task_file):
        with open(task_file, "w") as f:
            json.dump(
                {
                    "pending_task": "Open notepad and type 'FridayOS Self Healing Active'",
                    "status": "queued",
                },
                f,
            )

    with open(task_file, "r") as f:
        task_data = json.load(f)

    user_intent = task_data.get("pending_task", "")
    print(f"[*] Target Objective captured: '{user_intent}'")

    # -----------------------------------------------------------------
    # Feature 1: Long-Term Memory Vector Cache Lookup Engine
    # -----------------------------------------------------------------
    print("[*] Memory Core: Checking database vector cache for historical matches...")
    memory_results = macro_collection.query(query_texts=[user_intent], n_results=1)

    cached_code = None
    # Verify similarity threshold match
    if (
        memory_results
        and memory_results["documents"]
        and memory_results["documents"][0]
    ):
        distance = (
            memory_results["distances"][0][0] if memory_results["distances"] else 1.0
        )
        # If distance is low (under 0.35), it's highly semantically similar
        if distance < 0.35:
            cached_code = memory_results["documents"][0][0]
            print(
                f"[✔] Memory Core Match Found! (Semantic Distance: {distance:.4f}). Loading code instantly from disk cache..."
            )

    # -----------------------------------------------------------------
    # Execution Sandbox Loop with Adaptive Self-Healing
    # -----------------------------------------------------------------
    attempt = 1
    success = False
    last_error_log = ""
    generated_code = cached_code if cached_code else ""

    # Feature 2 Optimization: Try to proactively open application paths specified in text
    if "notepad" in user_intent.lower():
        bring_window_to_front("Notepad")

    while attempt <= MAX_HEALING_ATTEMPTS:
        # Skip generation step if we pulled a perfect match directly out of Chroma DB
        if cached_code and attempt == 1:
            print("[*] Running cached macro script asset on host desktop...")
        else:
            print(
                f"[Brain-2] Code Generation Attempt {attempt}/{MAX_HEALING_ATTEMPTS}..."
            )

            # If this is a retry loop, build a resilient self-healing prompt
            if attempt > 1:
                pyautogui.screenshot().save(f"error_screen_attempt_{attempt}.png")
                prompt = (
                    f"Your previous code execution crashed. Let's debug and fix it.\n\n"
                    f"TARGET TASK COMPLIANCE OBJECTIVE:\n{user_intent}\n\n"
                    f"THE PYTHON CODE THAT CAUGHT THE RUNTIME CRASH:\n{generated_code}\n\n"
                    f"WINDOWS EXECUTION TRACE LOG:\n{last_error_log}\n\n"
                    f"Review the crash trace log, analyze the error parameters, and output a corrected python script version."
                )
            else:
                prompt = f"FridayOS State & Targets:\n{user_intent}\n\nWrite a python script to accomplish this using pyautogui/screen control."

            raw_response = ask_local_brain(prompt)
            print(
                f"\n--- [OLLAMA RAW RESPONSE] ---\n{raw_response}\n-----------------------------\n"
            )
            print(
                f"\n---[DEBUG]Raw Model Output Start ---\n{raw_response}\n---[DEBUG]Raw Model Output End ---\n{raw_response}\n---[DEBUG]Raw Model Output End ---\n"
            )

            generated_code = extract_clean_code(raw_response)

        if not generated_code or len(generated_code) < 5:
            print(
                "[!] Failed to extract meaningful script blocks. Retrying execution loop..."
            )
            attempt += 1
            continue

        # Write execution target script asset to disk space
        runtime_script = "friday_executor.py"
        with open(runtime_script, "w", encoding="utf-8") as f:
            f.write(generated_code)

        result = subprocess.run(
            [sys.executable, runtime_script], capture_output=True, text=True
        )

        if result.returncode == 0:
            print(f"[✔] Script succeeded cleanly on attempt {attempt}!")
            success = True

            # Save to Long-Term Memory Core cache if generated freshly by Ollama
            if not cached_code:
                print(
                    "[*] Memory Core: Saving newly evolved macro blueprint to ChromaDB cache..."
                )
                macro_collection.add(
                    documents=[generated_code],
                    ids=[f"macro_{int(os.path.getmtime(task_file))}"],
                    metadatas=[{"intent": user_intent}],
                )
            break
        else:
            print(
                f"[❌] Attempt {attempt} crashed! Intercepting stack trace for healing loop..."
            )
            # If the cached script fails (e.g. coordinates shifted over time), break cache loop and force a fresh regenerate
            if cached_code:
                print(
                    "[!] Cached script asset is deprecated. Forcing deep model re-generation..."
                )
                cached_code = None
            last_error_log = (
                f"STDOUT STATUS:\n{result.stdout}\nSTDERR TRACK RES:\n{result.stderr}"
            )
            attempt += 1

    # Final telemetry logging back across the folder boundary
    status = "completed" if success else "failed"
    log_payload = {
        "status": status,
        "attempts_required": attempt if success else MAX_HEALING_ATTEMPTS,
        "from_cache": cached_code is not None,
        "output": result.stdout if success else "",
        "errors": last_error_log if not success else "",
    }

    with open(os.path.join(FRIDAY_OS_DIR, "friday_execution_log.json"), "w") as f:
        json.dump(log_payload, f, indent=4)

    print(f"[*] FridayOS execution bridge updated. Global Status: {status}")


if __name__ == "__main__":
    main()
